create table if not exists public.mantenimiento (
  id bigint generated by default as identity not null,
  placa_id bigint not null,
  tipo text null,
  km double precision null,
  hr double precision null,
  taller_id bigint null,
  fecha_entrada date null,
  fecha_salida date null,
  tipo_mantenimiento text null,
  actividad text null,
  nota text null,
  constraint mantenimiento_pkey primary key (id),
  constraint mantenimiento_placa_id_fkey foreign KEY (placa_id) references areas_placas (id),
  constraint mantenimiento_taller_id_fkey foreign KEY (taller_id) references talleres (id)
) TABLESPACE pg_default;

-- Trigger to set tipo_mantenimiento
create or replace function set_tipo_from_control_flota()
returns trigger as $$
begin
  -- Logic to be implemented based on requirements, placeholder for now
  -- NEW.tipo_mantenimiento = ...
  return NEW;
end;
$$ language plpgsql;

drop trigger if exists trg_set_tipo_mantenimiento on mantenimiento;
create trigger trg_set_tipo_mantenimiento BEFORE INSERT
or update OF placa_id on mantenimiento for EACH row
execute FUNCTION set_tipo_from_control_flota ();

-- Trigger to update horometro
create or replace function actualizar_horometro_desde_mantenimiento()
returns trigger as $$
begin
  -- Logic to be implemented
  return NEW;
end;
$$ language plpgsql;

drop trigger if exists trigger_actualizar_horometro_mant on mantenimiento;
create trigger trigger_actualizar_horometro_mant
after INSERT or DELETE or update on mantenimiento for EACH row
execute FUNCTION actualizar_horometro_desde_mantenimiento ();

-- Trigger to update days
create or replace function actualizar_dias_mantenimiento()
returns trigger as $$
begin
  -- Logic to be implemented
  return NEW;
end;
$$ language plpgsql;

drop trigger if exists trigger_dias_mantenimiento_mantenimiento on mantenimiento;
create trigger trigger_dias_mantenimiento_mantenimiento
after INSERT or update on mantenimiento for EACH row
execute FUNCTION actualizar_dias_mantenimiento ();
